title: 
description: 
theme: minima
plugins:
  - jekyll-seo-tag

# Exclude Obsidian's internal folder
exclude:
  - .obsidian

# Optional: Enable GitHub Flavored Markdown
markdown: kramdown
kramdown:
  input: GFM
